# 公共配置文件 - 所有服务共享的配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      # 配置消息总线的destination
      destination: springCloudBus
      
# Actuator端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,bus-refresh,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true
    bus-refresh:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 日志配置
logging:
  level:
    org.springframework.cloud.bus: DEBUG
    org.springframework.amqp: DEBUG
    com.neusoft: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/${spring.application.name}.log
    max-size: 10MB
    max-history: 30