server:
  port: 10100

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:elm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.po
  configuration:
    map-underscore-to-camel-case: true